config/routes.rb
Rails.application.routes.draw do
  # Autenticação de usuários
  devise_for :users
  mount TokenAuthenticateMe::Engine => TokenAuthenticateMe.configuration.mount_path
  get 'home/index'
  
  # Autenticação de administradores
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  # Rotas usuais
  root "welcome#index"
  resources :restaurants
  get "/order/index" => "order#index"
  get "/order/confirm" => "order#confirm"
  get "/order/:id/:index" => "order#update"
  resources :order
  get "/list/:id" => "home#list"
  get "/show_menu/:id" => "home#show_menu"
  get "/home/order/:id" => "home#order"
  get "/qtt/:op/:dish_number/:qtts/:restaurant_id" => "home#qtt"
  get "/:restaurant_id/:order_qtt" => "order#create"
  get "/bill" => "order#bill"
  post "/bill" => "order#bill"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  serialize :order_info, Array
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :Shopping
  validates :name, :image_link, :menu, presence: true
end

app/models/shopping.rb
class Shopping < ApplicationRecord
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :orders
  
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @shoppings = Shopping.all
  end

  def list
    restaurants = Restaurant.all
    @restaurants = []
    restaurants.each do |restaurant|
      @restaurants.push(restaurant) if restaurant.Shopping_id.to_s == params[:id]
    end
  end
  
  def show_menu
    @image_path = Restaurant.find(params[:id]).image_link
    @id = Restaurant.find(params[:id]).id
  end

  def order
    @menu = Restaurant.find(params[:id]).menu
    @qtts = []
    (@menu.split ",").size.times { @qtts.push(0) }
    @restaurant_id = params[:id]
  end

  def qtt
    @menu = Restaurant.find(params[:restaurant_id]).menu
    @id = params[:restaurant_id]
    qtts = params[:qtts].split "_"
    qtt = qtts[params[:dish_number].to_i].to_i 

    qtt_is_a_number = is_a_number qtts[params[:dish_number].to_i] 
    
    if ((@menu.split ",").size == qtts.size) && (qtt >= 0 && qtt < 100) && qtt_is_a_number
      qtts[params[:dish_number].to_i] = qtts[params[:dish_number].to_i].to_i + 1 if params[:op] == "+"
      qtts[params[:dish_number].to_i] = qtts[params[:dish_number].to_i].to_i - 1 if params[:op] == "-" && qtts[params[:dish_number].to_i].to_i > 0
      
      @qtts = qtts
      @restaurant_id = params[:restaurant_id]
      render :order    
    else
      render :invalid_qtt
    end
  end

  private
  def is_a_number string
    return true if string.to_i.to_s == string
    return false
  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  before_action :get_today_open_orders, only: %i[index confirm bill]

  def index
    @shipping = get_shipping
    @missing_orders_to_discount = 5 - (Order.where(open: false).size % 5)
    @discount = get_discount
  end

  def create
    
    destroy_old_orders

    @menu = Restaurant.find(params[:restaurant_id]).menu
    @restaurant_id = params[:restaurant_id]
    @qtts = (params[:order_qtt]).split "_"

    order_is_blank = @qtts.all? "0"

    if order_is_blank
      @qtts.map! {|qtt| qtt.to_i }
      return render "home/order"
    end

    @to_show_msg = true
        
    order_info = []
    menu = @menu.split ","
    qtt_is_valid = true

    @qtts.each_with_index do |qtt, index|
      if qtt.to_i > 0
        dish = ((menu[index]).split "/")[0]
        price = ((menu[index]).split "/")[1]
        order_info.push([dish, price, qtt])  
      end
      
      if qtt.to_i < 0 || qtt.to_i > 100 || !(is_a_number qtt)
        qtt_is_valid = false
      end   
    end

    order = Order.new(order_info: order_info,
                      user_id: current_user.id,
                      restaurant: params[:restaurant_id],
                      open: true)
    

    if order.save && qtt_is_valid
      @msg = "Pedido enviado ao carrinho."
    else
      @msg = "Não foi possível efetuar o pedido."
    end

    render "home/order"
  end

  def confirm
    @total = 0
       
    @today_open_orders.each do |order|
      order.order_info.each do |cost|
        @total += cost[1].to_f * cost[2].to_f
      end
    end

    @total -= @total * get_discount if (Order.where(open: false).size % 5) == 0
    @total += get_shipping
  end

  def bill
    @today_open_orders.each do |order|
      order.update(open: false)
    end
  end

  def update
    order = Order.find(params[:id])
    order_info = order.order_info
    
    return redirect_to order_index_path unless is_a_valid_index params[:index], order_info.size
    
    order_info.delete_at(params[:index].to_i)
    order.update(order_info: order_info)
    
    destroy params[:id] if order_info.size == 0

    redirect_to order_index_path
  end

  private
  def destroy_old_orders
    Order.where(user_id: current_user.id, open: true).each do |order|
      order.destroy if order.created_at.before? (Date.new(Time.now.year, Time.now.month, Time.now.day))
    end
  end

  def destroy id
    Order.find(id).destroy
  end

  def get_today_open_orders
    today = Time.now.day
    all_orders = Order.where(user_id: current_user.id, open: true)
    @today_open_orders = []

    all_orders.each do |order|
      @today_open_orders.push order if order.created_at.day == today 
    end
  end

  def get_discount
    return 0.2
  end

  def get_shipping
    return 10
  end

  def is_a_number string
    return true if string.to_i.to_s == string
    return false
  end

  def is_a_valid_index index, size
    (is_a_number index) && index.to_i >= 0 && index.to_i < size
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/error.html.erb
<h1>Página não encontrada</h1>

app/views/home/index.html.erb
<div>
  <h1>Shoppings</h1>
  <% @shoppings.each do |shopping| %>
    <div class="shoppings">
      <h2><%= link_to shopping.name, "/list/#{shopping.id}", class: "shopping-names" %></h2>
    </div>
  <% end %>
</div>

app/views/home/invalid_qtt.html.erb
<h1> Quantidade inválida. </h1>

<div id="back-to-order"><%= link_to "Retornar para os pedidos", "/home/order/#{@id}", class: "btn btn-primary" %></div>

app/views/home/list.html.erb
<h1>Restaurantes</h1>
<% @restaurants.each do |restaurant| %>
  <div class="restaurants">
    <h2><%= link_to restaurant.name, "/show_menu/#{restaurant.id}", class: "restaurant-names" %></h2>
  </div>
<% end %>

app/views/home/order.html.erb
<% total = 0 %>
<% order_qtt = 0 %>

<% if @to_show_msg %>
  <div id="order-sended-message"><h2 id="cart-message"><%= @msg %></h2></div>
<% end %>

<table class="table table-borderless">
  <thead>
    <th>Prato</th>
    <th>Preço</th>
    <th>Quantidade</th>
    <th>Adicionar</th>
    <th>Remover</th>
  </thead>
  <tbody>
    
      <% (@menu.split ",").each_with_index do |dish, dish_number| %>
        <% temp = dish.split "/" %>
        <% dish_name = temp[0] %>
        <% dish_price = temp[1] %> 

        <tr>  
          <td><%= dish_name %></td>
          <td>R$<%= dish_price %></td>
          <td><%= @qtts[dish_number] %></td>
          <% qtts = @qtts.join("_") %>
          <% plus = "/qtt/+/#{dish_number}/#{qtts}/#{@restaurant_id}" %>
          <% minus = "/qtt/-/#{dish_number}/#{qtts}/#{@restaurant_id}" %>
          <td class="op-button"><a href=<%=plus%>><%= fa_icon "plus", id: "plus" %></a></td>
          <td class="op-button"><a href=<%=minus%>><%= fa_icon "minus", id: "minus" %></td>
        </tr>

        <% total += dish_price.to_f * @qtts[dish_number].to_f %>
        <% order_qtt = qtts %>
      <% end %>

      <tr>
        <td class="total-table"><h2 id="total-table-text">Total</h2></td>
        <td class="total-table">R$<%= total.round(2) %></td>
      </tr>
  <tbody>
</table>

<%= link_to "Adicionar ao carrinho", "/#{@restaurant_id}/#{order_qtt}", class: "btn btn-primary", id: "add-to-cart" %>

app/views/home/order_confirmation.html.erb
<nav class="navigation">
  <div class="navigation_bar">
    <div class="navigation_buttons" id="home"><h1><%= link_to "Home", root_path %></h1></div>
    <div class="navigation_buttons" id="shoppings"><h1><%= link_to "Lista de Shoppings", home_index_path %></h1></div>
  </div>
</nav>

<h1> Confirme seu pedido </h1>
<% @order.each_with_index do |dish, index| %>
  <h2><%= (dish.split "/")[0] %> R$<%= (dish.split "/")[1] %> Quantidade: <%= @order_qtt[index] %></h2>
<% end %>
<h2> Total: R$<%= @total.round(2) %> </h2>

app/views/home/shopping_list.html.erb
<h1>Restaurantes</h1>
<% @restaurants.each do |restaurant| %>
  <div class="restaurant">
    <p><%= restaurant.name %></p>
  </div>
<% end %>

app/views/home/show_menu.html.erb
<div id="order">
  <h1><%= link_to "Faça o seu pedido", "/home/order/#{@id}" , id: "order-request-link" %></h1>
</div>

<div id="menu">
  <%= image_tag (@image_path), class: "img-fluid" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yammy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if user_signed_in? %>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
          <div class="col-3"></div>
          <div class="col-6">
            <div class="row">
              <div class="container-fluid">
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item"><h1><%= link_to "Home", root_path, class: "btn btn-primary", id: "home-button" %></h1></li>
                    <li class="nav-item"><h1><%= link_to "Lista de Shoppings", home_index_path, class: "btn btn-primary", id: "shoppings-button" %></h1></li>
                    <li class="nav-item"><h1><%= link_to "Ver Carrinho", "/order/index", class: "btn btn-primary", id: "cart-button" %></h1></li>
                    <li class="nav-item"><h1><%= link_to "Sair do sistema", destroy_user_session_path, method: :delete, class: "btn btn-primary", id: "logout-button" %></h1></li>
                  </ul>
                </div> 
              </div>   
            </div>
            <div class="col-3"></div>
          </div>
        </nav>
      <% elsif user_signed_in? == false %>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
          <div class="col-3"></div>
          <div class="col-6">
            <div class="row">
              <div class="container-fluid">
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item"><h1><%= link_to "Login", home_index_path,class: "btn btn-primary", id: "login-button" %></h1></li>
                    <li class="nav-item"><h1><%= link_to "Cadastro", new_user_registration_path, class: "btn btn-primary", id: "subscribe-button" %></h1></li>
                  </ul>
                </div> 
              </div>   
            </div>
            <div class="col-3"></div>
          </div>
        </nav>
      <% end %>
    </header>

    <main>
      <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
          <%= yield %>
        </div>
        <div class="col-3"></div>
      <div class="row">
    </main>
  </body>
</html>

app/views/order/bill.html.erb
<h1>O seu pedido foi finalizado com sucesso!</h1>
<div id="back-to-order"><h2><%= link_to "Voltar", home_index_path, class: "btn btn-primary" %></h2></div>

app/views/order/confirm.html.erb
<h1>Insira seus dados</h1>

<%= form_with url: "/bill" do |f| %>
  <div>
    <div class="confirm-labels"><%= f.label :titular, class: 'form-label' %></div>
    <%= f.text_field :nome, class: 'form-control' %>
  </div>
  
  <div>
    <div class="confirm-labels"><%= f.label :cpf, "CPF", class: 'form-label' %></div>
    <%= f.text_field :user_id, class: 'form-control' %>
  </div>
  
  <div>
    <div class="confirm-labels"><%= f.label :numero_do_cartao, "Número do Cartão" , class: 'form-label' %></div>
    <%= f.text_field :card_num, class: 'form-control' %>
  </div>
  
  <div>
    <div class="confirm-labels"><%= f.label :data_de_expiracao, "Data de Expiração",class: 'form-label' %></div>
    <% date = Time.now %>
    <% date.strftime("%d/%m/%Y") %>
    <%= date_field(:exp_date, :date, min: "#{date.year}-#{date.month}-#{date.day}", class: "form-control")%>
  </div>
  
  <div>
    <div class="confirm-labels"><%= f.label :csv, "CSV",class: 'form-label' %></div>
    <%= f.text_field :csv, class: 'form-control' %>
  </div>

  <div>
    <div class="confirm-labels"><%= f.label :cellphone, "Número para contato", class: 'form-label' %></div>
    <%= f.text_field :cellphone, class: 'form-control' %>
  </div>
  <div>
    <h2 id="total-message">O total é R$<%= @total.round(2) %></h2>
    <%= f.submit "Pagar", class: "btn btn-primary" %>  
  </div>
<% end %>

app/views/order/index.html.erb
<h1> Pedidos de Hoje </h1>

<% if @missing_orders_to_discount < 5 %>
  <div class="discount-status"><h2 class="discount-status-msg"> Faltam <%= @missing_orders_to_discount %> pedidos para você ganhar um desconto. </h2></div>
<% elsif @missing_orders_to_discount == 5 && @today_open_orders.size > 0 %>
  <div class="discount-status"><h2 class="discount-status-msg"> Esse pedido terá 20% de desconto </h2></div>
<% else %>
  <div class="discount-status"><h2 class="discount-status-msg"> Seu próximo pedido terá desconto </h2></div>
<% end %>

<% total = 0 %>
<% restaurant_total = 0 %>

<% @today_open_orders.each do |order| %>
  <div class="restaurant-names-table"><h2 id="restaurant-names"><%= Restaurant.find(order.restaurant.to_i).name %> do <%= Restaurant.find(order.restaurant.to_i).Shopping.name %></h2></div>
  <table class="table table-borderless">
    <thead>
      <th>Prato</th>
      <th>Preço</th>
      <th>Quantidade</th>
      <th>Remover</th>
    </thead>
    <tbody>
      
        <% order.order_info.each_with_index do |info, index| %>
          <% dish = info[0] %>
          <% price = info[1] %>
          <% qtt = info[2] %>
          <% restaurant_total += price.to_f * qtt.to_f %>
          <% minus = "/order/#{order.id}/#{index}" %>
          <tr>
            <td><%= dish %></td>
            <td>R$<%= price %></td>
            <td id="quantity-cart"><%= qtt %></td>
            <td class="op-button" id="minus-cart"><a href=<%=minus%> data-confirm="Gostaria de remover esse prato?"><%= fa_icon "minus", id: "minus" %></td>
          </tr>
        <% end %>         

        <tr>
          <td class="total-table" ><h2 id="total-table-text">Total</h2></td>
          <td class="total-table">R$<%= restaurant_total.round(2) %></td>
        </tr>

        <% total +=  restaurant_total%>
        <% restaurant_total = 0 %>
    <tbody>
  </table>
<% end %>  

<% if total > 0 %>
  <h2 class="footer-cart-messages" id="shipping-message">Será acrescido um frete de R$10,00 ao valor do pedido</h2>
  <h2 class="footer-cart-messages">O total é de R$<%= (total + @shipping).round(2) %></h2>
  <% if @missing_orders_to_discount == 5 %>
    <% total -= total * @discount %>
    <h2 class="footer-cart-messages">O total com desconto é de R$<%= (total + @shipping).round(2) %></h2>
  <% end %>
  <div><h2 class="footer-cart-messages"><%= link_to "Finalizar Pedido(s)", "/order/confirm", class: "btn btn-primary" %></h2></div>
<% else %>
  <h2 class="footer-cart-messages">Você não realizou um pedido ainda.</h2>
  <div class="make-order-button"><h2><%= link_to "Fazer um pedido", home_index_path, class: "btn btn-primary" %></h2></div>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Login", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Cadastre-se", new_registration_path(resource_name), id: 'subscribe-link', class: 'btn btn-primary' %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Esqueceu sua senha?", new_password_path(resource_name), id: 'password-redefinition-link', class: 'btn btn-primary' %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/welcome/index.html.erb
<div class="row">  
  <h1 id="welcome-text">Bem vindo ao Yammy!</h1>
</div>

<div >
  <p>
    <h3 class="welcome-text">Yammy é um sistema que visa facilitar a interação dos restaurantes com os clientes.</h3>
  </p>
  <p>
    <h3 class="welcome-text">Clientes podem fazer seus pedidos de forma mais fluída e sem complicações envolvendo a entrada e saída entre cada Shopping e Restaurantes.</h3>
  </p>
  <p>
    <h3 class="welcome-text">Restaurantes podem gerenciar melhor seus pedidos e clientes com uma tabela de fácil leitura e manutenção.</h3>
  </p>
</div>